const model = {
  app: {
    // app: document.getElementById("app"),
    adminLoggedIn: false,
    currentPage: "frontPage", // selectionPage, storeFrontPage, writeReviewPage, loginPage, adminPage,
    pages: ["frontPage", "selectionPage", "storeFrontPage", "writeReviewPage", "loginPage", "registerUserPage", "adminPage"],
    currentCity: 0,
    // currentUser: "",
  },

  viewState: {

    storeFrontPage: {
      selectedCity: 0,
      selectedStore: 0,
      adminReview: "",
      adminStore: "",
    },

    writeReviewPage: {
      userScore: undefined,
      userReview: "",
      userName: "",
      userPicture: [],
      allergyList: {
        vegan: false,
        milk: false,
        nuts: false,
        wheat: false,
      },
    },

    loginPage: {
      username: "",
      userPassword: "",
      loginInvalid: "",
    },

    registerUserPage:{
      username:"",
      userPassword: "",
      confirmPassword: "",
    }
  },

  // data
  data: {
    credentials: [
      {
        name: "Anita",
        password: "anita",
      },
    ],

    cities: [

      { name: "Oslo",  
      
        store: 
        [
          {
            reviews: 
              [
                {
                  name: "Anna Hansen",
                  pictures: [""],
                  score: 5,
                  reviewText: "Fantastisk kaffe og hyggelig atmosfære!",
                  date: "2026-02-14",
                  likes: 12,
                  allergyList: {
                        vegan: false,
                        milk: true,
                        nuts: false,
                        wheat: false,
                               },
                },
                {
                  name: "Jonas Berg",
                  pictures: ["Media/Cities/Oslo/Bakeri/Kundebilder/Kundebilde3.jpg"],
                  score: 4,
                  reviewText: "God cappuccino, men litt dyrt.",
                  date: "2026-02-10",
                  likes: 5,
                  allergyList: {
                        vegan: false,
                        milk: true,
                        nuts: false,
                        wheat: false,
                               },
                },
            ],
              
            info: 
              {
                city: "Oslo",
                storeName: "Nordlys Kafé",
                type: "cafe",
                pictures: ["Media/Cities/Oslo/Bakeri/Bakeri4.jpg"],
                address: "Karl Johans gate 15",
                phone: 22334455,
                email: "kontakt@nordlyskafe.no",
                averageScore: 4.5,
                reviewAmount: 120,
                link: "https://nordlyskafe.no",
            },
          },

          {
            reviews: 
            [
              {
                name: "Maria Olsen",
                pictures: ["Media/Cities/Oslo/Bakeri/Kundebilder/Kundebilde1.jpg"],
                score: 4,
                reviewText: "Ok plass for lunch!",
                date: "2026-01-20",
                likes: 20,
                allergyList: {
                        vegan: true,
                        milk: false,
                        nuts: true,
                        wheat: false,
                               },
              },
            ],
            
            info: 
            {
              city: "Oslo",
              storeName: "Fjell Bakeri",
              type: "bakery",
              pictures: ["Media/Cities/Oslo/Bakeri/Bakeri7.jpg"],
              address: "Bryggen 8",
              phone: 55667788,
              email: "post@fjellbakeri.no",
              averageScore: 4.8,
              reviewAmount: 85,
              link: "https://fjellbakeri.no",
            },
          },

          {
            reviews: 
            [
              {
                name: "Erik Johansen",
                pictures: [],
                score: 3,
                reviewText: "Greit sted, men pizzaen var litt tørr.",
                date: "2026-03-01",
                likes: 2,
                allergyList: {
                        vegan: true,
                        milk: false,
                        nuts: false,
                        wheat: true,
                               },
              },
              {
                name: "Lise Nilsen",
                pictures: ["Media/Cities/Oslo/Resturant/Kundebilder/Kundebilde4.jpg"],
                score: 4,
                reviewText: "God service og hyggelig personale.",
                date: "2026-03-03",
                likes: 4,
                allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
              },
            ],
            
            info: 
            {
              city: "Oslo",
              storeName: "PizzaHjørnet",
              type: "restaurant",
              pictures: ["Media/Cities/Oslo/Resturant/Resturant2.jpg"],
              address: "Munkegata 12",
              phone: 77889900,
              email: "hei@pizzahjornet.no",
              averageScore: 3.8,
              reviewAmount: 200,
              link: "https://pizzahjornet.no",
            },
          },

          {
            reviews: 
            [
              {
                name: "Sofie Larsen",
                pictures: ["Media/Cities/Oslo/Bakeri/Kundebilder/Kundebilde4.jpg"],
                score: 5,
                reviewText: "Utrolig gode kaker og flott presentasjon!",
                date: "2026-02-25",
                likes: 15,
                allergyList: {
                        vegan: false,
                        milk: true,
                        nuts: true,
                        wheat: false,
                               },
              },
            ],
            
            info: 
            {
              city: "Oslo",
              storeName: "Arktisk Søtt",
              type: "bakery",
              pictures: ["Media/Cities/Oslo/Bakeri/Bakeri8.jpg"],
              address: "Storgata 22",
              phone: 99887766,
              email: "kontakt@arktisksott.no",
              averageScore: 4.9,
              reviewAmount: 60,
              link: "https://arktisksott.no",
            },
          },
          
          {
            reviews: 
            [
              {
                name: "Daniel Pedersen",
                pictures: [""],
                score: 4,
                reviewText: "Veldig bra burger og fries!",
                date: "2026-03-10",
                likes: 6,
                allergyList: {
                        vegan: true,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
              },
            ],
            
            info: 
            {
              city: "Oslo",
              storeName: "BurgerBua",
              type: "restaurant",
              pictures: ["Media/Cities/Oslo/Resturant/Resturant3.jpg"],
              address: "Øvre Holmegate 5",
              phone: 66778899,
              email: "post@burgerbua.no",
              averageScore: 4.2,
              reviewAmount: 140,
              link: "https://burgerbua.no",
            },
          },
          
          {
            reviews: 
            [
              {
                name: "Henrik Solberg",
                pictures: ["Media/Cities/Oslo/Bakeri/Kundebilder/Kundebilde6.jpg"],
                score: 5,
                reviewText: "Perfekt sted for å jobbe og slappe av.",
                date: "2026-03-15",
                likes: 9,
                allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
              },
            ],
            
            info: 
            {
              city: "Oslo",
              storeName: "Nord Kaffe",
              type: "cafe",
              pictures: ["Media/Cities/Oslo/Bakeri/Bakeri22.jpg"],
              address: "Markedsgata 3",
              phone: 11223344,
              email: "hei@nordkaffe.no",
              averageScore: 4.7,
              reviewAmount: 45,
              link: "https://nordkaffe.no",
            },
          },
        ], 
      },
      { name: "Bergen",
    
    
        store: [
          {
            reviews: [
              {
                name: "Maria L.",
                pictures: ["Media/Cities/Bergen/Bakeri/Kundebilder/Kundebilde7.jpg"],
                score: 5,
                reviewText: "Fantastiske boller og hyggelig personale!",
                date: "2026-02-12",
                likes: 3,
                allergyList: {
                        vegan: false,
                        milk: true,
                        nuts: false,
                        wheat: true,
                               },
              },
              {
                name: "Jonas K.",
                pictures: ["Media/Cities/Bergen/Bakeri/Kundebilder/Kundebilde8.jpg"],
                score: 4,
                reviewText: "God kaker her, litt travelt.",
                date: "2026-01-20",
                likes: 1,
                allergyList: {
                        vegan: true,
                        milk: true,
                        nuts: true,
                        wheat: false,
                               },
              },
              {
                name: "Ingrid S.",
                pictures: [""],
                score: 5,
                reviewText: "Elsker croissantene her!",
                date: "2026-03-02",
                likes: 4,
                allergyList: {
                        vegan: false,
                        milk: true,
                        nuts: true,
                        wheat: true,
                               },
              },
              {
                name: "Per H.",
                pictures: [""],
                score: 4,
                reviewText: "Koselig sted og gode priser.",
                date: "2026-02-25",
                likes: 2,
                allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
              },
            ],
            info: {
              city: "Bergen",
              storeName: "Solglimt Bakeri",
              type: "bakery",
              pictures: ["Media/Cities/Bergen/Bakeri/Bakeri6.jpg"],
              address: "Bryggen 12",
              phone: 55512345,
              email: "post@solglimt.no",
              averageScore: 4.5,
              reviewAmount: 4,
              link: "https://solglimt.no",
            },
          },

          {
            reviews: [
              {
                name: "Anne T.",
                pictures: [""],
                score: 5,
                reviewText: "Beste cappuccino i byen.",
                date: "2026-03-01",
                likes: 5,
                allergyList: {
                        vegan: false,
                        milk: true,
                        nuts: false,
                        wheat: false,
                               },
              },
              {
                name: "Lars E.",
                pictures: ["Media/Cities/Bergen/Bakeri/Kundebilder/Kundebilde10.jpg"],
                score: 4,
                reviewText: "Veldig bra atmosfære.",
                date: "2026-02-14",
                likes: 2,
                allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
              },
              {
                name: "Ole M.",
                pictures: [""],
                score: 5,
                reviewText: "Perfekt sted å jobbe fra.",
                date: "2026-02-18",
                likes: 3,
                allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
              },
            ],
            info: {
              city: "Bergen",
              storeName: "Fjellro Kafé",
              type: "cafe",
              pictures: ["Media/Cities/Bergen/Bakeri/Bakeri12.jpg"],
              address: "Torgallmenningen 5",
              phone: 55567890,
              email: "hei@fjellro.no",
              averageScore: 4.5,
              reviewAmount: 4,
              link: "https://fjellro.no",
            },
          },

          {
            reviews: [
              {
                name: "Sofie B.",
                pictures: ["Media/Cities/Bergen/Resturant/Kundebilder/Kundebilde9.jpg"],
                score: 5,
                reviewText: "Utrolig god pizza!",
                date: "2026-03-03",
                likes: 6,
                allergyList: {
                        vegan: true,
                        milk: true,
                        nuts: false,
                        wheat: true,
                               },
              },
              {
                name: "Daniel W.",
                pictures: [""],
                score: 4,
                reviewText: "God mat, litt lang ventetid.",
                date: "2026-02-27",
                likes: 2,
                allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
              },
              {
                name: "Emma R.",
                pictures: [""],
                score: 5,
                reviewText: "Fantastisk service.",
                date: "2026-02-10",
                likes: 4,
                allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
              },
            ],
            info: {
              city: "Bergen",
              storeName: "Bryggen Restaurant",
              type: "restaurant",
              pictures: ["Media/Cities/Bergen/Resturant/Resturant9.jpg"],
              address: "Bryggen 25",
              phone: 55511223,
              email: "booking@bryggenrest.no",
              averageScore: 4.5,
              reviewAmount: 4,
              link: "https://bryggenrest.no",
            },
          },

          {
            reviews: [
              {
                name: "Mats O.",
                pictures: [""],
                score: 4,
                reviewText: "Veldig gode kaker.",
                date: "2026-02-05",
                likes: 2,
                allergyList: {
                        vegan: false,
                        milk: true,
                        nuts: true,
                        wheat: false,
                               },
              },
              {
                name: "Elise V.",
                pictures: ["Media/Cities/Bergen/Bakeri/Kundebilder/Kundebilde9.jpg"],
                score: 5,
                reviewText: "Beste bakeriet i Bergen!",
                date: "2026-03-04",
                likes: 5,
                allergyList: {
                        vegan: false,
                        milk: true,
                        nuts: false,
                        wheat: false,
                               },
              },
              {
                name: "Thomas G.",
                pictures: [""],
                score: 4,
                reviewText: "God kvalitet, litt dyrt.",
                date: "2026-02-19",
                likes: 1,
                allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
              },
              {
                name: "Nora P.",
                pictures: [""],
                score: 5,
                reviewText: "Elsker utvalget her.",
                date: "2026-01-28",
                likes: 3,
                allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
              },
            ],
            info: {
              city: "Bergen",
              storeName: "Bybakeriet",
              type: "bakery",
              pictures: ["Media/Cities/Bergen/Bakeri/Bakeri5.jpg"],
              address: "Marken 8",
              phone: 55533445,
              email: "kontakt@bybakeriet.no",
              averageScore: 4.5,
              reviewAmount: 4,
              link: "https://bybakeriet.no",
            },
          },

          {
            reviews: [
              {
                name: "Fredrik L.",
                pictures: ["Media/Cities/Bergen/Resturant/Kundebilder/Kundebilde11.jpg"],
                score: 5,
                reviewText: "Fantastisk burger!",
                date: "2026-03-06",
                likes: 4,
                allergyList: {
                        vegan: true,
                        milk: false,
                        nuts: false,
                        wheat: true,
                               },
              },
              {
                name: "Sara D.",
                pictures: ["Media/Cities/Bergen/Resturant/Kundebilder/Kundebilde12.jpg"],
                score: 4,
                reviewText: "God mat og hyggelig sted.",
                date: "2026-02-16",
                likes: 2,
                allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
              },
              {
                name: "Kristian F.",
                pictures: [""],
                score: 4,
                reviewText: "Bra service.",
                date: "2026-01-19",
                likes: 1,
                allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
              },
              {
                name: "Julie A.",
                pictures: [""],
                score: 5,
                reviewText: "Kommer definitivt tilbake.",
                date: "2026-02-28",
                likes: 3,
                allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
              },
            ],
            info: {
              city: "Bergen",
              storeName: "Vestkanten Grill",
              type: "restaurant",
              pictures: ["Media/Cities/Bergen/Resturant/Resturant7.jpg"],
              address: "Vestkanten 3",
              phone: 55566778,
              email: "post@vestkantengrill.no",
              averageScore: 4.5,
              reviewAmount: 4,
              link: "https://vestkantengrill.no",
            },
          },
        ],

      }, 
      { name: "Trondheim",
      store: [
        {
          reviews: [
            {
              name: "Lars Nilsen",
              pictures: [""],
              score: 5,
              reviewText: "Veldig koselig sted og god kaffe!",
              date: "2026-03-01",
              likes: 8,
              allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
            },
            {
              name: "Ingrid Solberg",
              pictures: [""],
              score: 4,
              reviewText: "Hyggelig service, men litt travelt.",
              date: "2026-02-25",
              likes: 3,
              allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
            },
          ],
          info: {
            city: "Trondheim",
            storeName: "Fjord Kafé",
            type: "cafe",
            pictures: ["Media/Cities/Trondheim/Bakeri/Bakeri1.jpg"],
            address: "Munkegata 10",
            phone: 73567890,
            email: "post@fjordkafe.no",
            averageScore: 4.3,
            reviewAmount: 58,
            link: "https://fjordkafe.no",
          },
        },

        {
          reviews: [
            {
              name: "Ole Johansen",
              pictures: ["Media/Cities/Trondheim/Bakeri/Kundebilder/Kundebilde17.jpg"],
              score: 5,
              reviewText: "Beste bakverk i byen!",
              date: "2026-03-05",
              likes: 15,
              allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
            },
          ],
          info: {
            city: "Trondheim",
            storeName: "Bakst & Glede",
            type: "bakery",
            pictures: ["Media/Cities/Trondheim/Bakeri/Bakeri2.jpg"],
            address: "Olav Tryggvasons gate 22",
            phone: 73881234,
            email: "hei@bakstoglede.no",
            averageScore: 4.8,
            reviewAmount: 210,
            link: "https://bakstoglede.no",
          },
        },

        {
          reviews: [
            {
              name: "Mats Eriksen",
              pictures: [""],
              score: 5,
              reviewText: "Fantastisk pizza!",
              date: "2026-03-02",
              likes: 11,
              allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
            },
          ],
          info: {
            city: "Trondheim",
            storeName: "PizzaHjørnet",
            type: "restaurant",
            pictures: ["Media/Cities/Trondheim/Resturant/Resturant18.jpg"],
            address: "Kongens gate 30",
            phone: 73887766,
            email: "post@pizzahjornet.no",
            averageScore: 4.6,
            reviewAmount: 140,
            link: "https://pizzahjornet.no",
          },
        },

        {
          reviews: [
            {
              name: "Sofie Aas",
              pictures: ["Media/Cities/Trondheim/Bakeri/Kundebilder/Kundebilde19.jpg"],
              score: 4,
              reviewText: "God kaffe, litt lite sitteplasser.",
              date: "2026-03-03",
              likes: 4,
              allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
            },
            {
              name: "Henrik Dahl",
              pictures: [""],
              score: 5,
              reviewText: "Perfekt sted for studier.",
              date: "2026-03-01",
              likes: 7,
              allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
            },
          ],
          info: {
            city: "Trondheim",
            storeName: "Student Kaféen",
            type: "cafe",
            pictures: ["Media/Cities/Trondheim/Bakeri/Bakeri19.jpg"],
            address: "Elgeseter gate 1",
            phone: 73559988,
            email: "kontakt@studentkafeen.no",
            averageScore: 4.5,
            reviewAmount: 76,
            link: "https://studentkafeen.no",
          },
        },

        {
          reviews: [
            {
              name: "Daniel Vik",
              pictures: ["Media/Cities/Trondheim/Resturant/Kundebilder/Kundebilde7.jpg"],
              score: 5,
              reviewText: "Utrolig gode burgere!",
              date: "2026-03-06",
              likes: 13,
              allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
            },
            {
              name: "Ida Moe",
              pictures: [""],
              score: 4,
              reviewText: "Saftig burger, men litt ventetid.",
              date: "2026-03-04",
              likes: 6,
              allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
            },
          ],
          info: {
            city: "Trondheim",
            storeName: "Burgerhjørnet",
            type: "restaurant",
            pictures: ["Media/Cities/Trondheim/Resturant/Resturant17.jpg"],
            address: "Thomas Angells gate 14",
            phone: 73995544,
            email: "hei@burgerhjornet.no",
            averageScore: 4.7,
            reviewAmount: 165,
            link: "https://burgerhjornet.no",
          },
        },

        {
          reviews: [
            {
              name: "Erik Strand",
              pictures: [""],
              score: 5,
              reviewText: "Beste kaffebønnene jeg har smakt!",
              date: "2026-03-07",
              likes: 10,
              allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
            },
            {
              name: "Maria Haug",
              pictures: ["Media/Cities/Trondheim/Bakeri/Kundebilder/Kundebilde20.jpg"],
              score: 5,
              reviewText: "Fantastisk kvalitet og service.",
              date: "2026-03-05",
              likes: 8,
              allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
            },
            {
              name: "Thomas Bye",
              pictures: [""],
              score: 4,
              reviewText: "Litt dyrt, men verdt det.",
              date: "2026-03-02",
              likes: 5,
              allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
            },
          ],
          info: {
            city: "Trondheim",
            storeName: "Kaffebrenneriet Trondheim",
            type: "cafe",
            pictures: ["Media/Cities/Trondheim/Bakeri/Bakeri20.jpg"],
            address: "Nedre Bakklandet 20",
            phone: 73889977,
            email: "kontakt@kaffebrenneriet.no",
            averageScore: 4.8,
            reviewAmount: 198,
            link: "https://kaffebrenneriet.no",
          },
        },
      ],
      },
      { name: "Tromsø",
        store: [
                {
                  reviews: [
                    {
                      name: "Maja Olsen",
                      pictures: [""],
                      score: 5,
                      reviewText: "Helt fantastisk kaffe og utsikt!",
                      date: "2026-03-10",
                      likes: 14,
                      allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                    },
                    {
                      name: "Henrik Johansen",
                      pictures: ["Media/Cities/Tromsø/Bakeri/Kundebilder/Kundebilde16.jpg"],
                      score: 2,
                      reviewText: "Altfor dyrt for det du får.",
                      date: "2026-03-08",
                      likes: 3,
                      allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                    },
                    {
                      name: "Silje Nilsen",
                      pictures: [""],
                      score: 4,
                      reviewText: "God stemning, men litt kaldt inne.",
                      date: "2026-03-06",
                      likes: 6,
                      allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                    },
                  ],
                  info: {
                    city: "Tromsø",
                    storeName: "Nordlys Kaffebar",
                    type: "cafe",
                    pictures: ["Media/Cities/Tromsø/Bakeri/Bakeri22.png"],
                    address: "Storgata 22",
                    phone: 77665544,
                    email: "hei@nordlyskaffe.no",
                    averageScore: 3.9,
                    reviewAmount: 87,
                    link: "https://nordlyskaffe.no",
                  },
                },

                {
                  reviews: [
                    {
                      name: "Per Hansen",
                      pictures: [""],
                      score: 1,
                      reviewText: "Dårlig service og kald mat.",
                      date: "2026-03-11",
                      likes: 9,
                      allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                    },
                    {
                      name: "Anna Berg",
                      pictures: ["Media/Cities/Tromsø/Resturant/Kundebilder/Kundebilde21.jpg"],
                      score: 3,
                      reviewText: "Helt ok, men ikke noe spesielt.",
                      date: "2026-03-09",
                      likes: 4,
                      allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                    },
                  ],
                  info: {
                    city: "Tromsø",
                    storeName: "Arktisk Bites",
                    type: "restaurant",
                    pictures: ["Media/Cities/Tromsø/Resturant/Resturant14.jpg"],
                    address: "Grønnegata 10",
                    phone: 77889900,
                    email: "post@arktiskbites.no",
                    averageScore: 2.8,
                    reviewAmount: 54,
                    link: "https://arktiskbites.no",
                  },
                },

                {
                  reviews: [
                    {
                      name: "Ingrid Moe",
                      pictures: [""],
                      score: 4,
                      reviewText: "Veldig god mat, litt lang ventetid.",
                      date: "2026-03-10",
                      likes: 7,
                      allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                    },
                    {
                      name: "Jonas Dahl",
                      pictures: ["Media/Cities/Tromsø/Resturant/Kundebilder/Kundebilde19.jpg"],
                      score: 3,
                      reviewText: "Bra, men ikke wow.",
                      date: "2026-03-08",
                      likes: 2,
                      allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                    },
                    {
                      name: "Kari Lie",
                      pictures: [""],
                      score: 5,
                      reviewText: "Elsker dette stedet!",
                      date: "2026-03-07",
                      likes: 11,
                      allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                    },
                  ],
                  info: {
                    city: "Tromsø",
                    storeName: "Isbjørn Burger",
                    type: "restaurant",
                    pictures: ["Media/Cities/Tromsø/Resturant/Resturant13.jpg"],
                    address: "Storgata 45",
                    phone: 77881122,
                    email: "hei@isbjornburger.no",
                    averageScore: 4.6,
                    reviewAmount: 143,
                    link: "https://isbjornburger.no",
                  },
                },

                {
                  reviews: [
                    {
                      name: "Sofie Lund",
                      pictures: ["Media/Cities/Tromsø/Bakeri/Kundebilder/Kundebilde14.jpg"],
                      score: 5,
                      reviewText: "Utrolig gode kaker!",
                      date: "2026-03-11",
                      likes: 12,
                      allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                    },
                    {
                      name: "Mats Eriksen",
                      pictures: ["Media/Cities/Tromsø/Bakeri/Kundebilder/Kundebilde15.jpg"],
                      score: 4,
                      reviewText: "God smak, men litt dyrt.",
                      date: "2026-03-09",
                      likes: 4,
                      allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                    },
                    {
                      name: "Ida Hansen",
                      pictures: [""],
                      score: 1,
                      reviewText: "Tørr kake og dårlig service.",
                      date: "2026-03-06",
                      likes: 7,
                      allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                    },
                  ],
                  info: {
                    city: "Tromsø",
                    storeName: "Søt Fristelse",
                    type: "bakery",
                    pictures: ["Media/Cities/Tromsø/Bakeri/Bakeri15.jpg"],
                    address: "Storgata 8",
                    phone: 77885533,
                    email: "hei@sotfristelse.no",
                    averageScore: 3.3,
                    reviewAmount: 67,
                    link: "https://sotfristelse.no",
                  },
                },
              ], 
      },
      { name: "Stavanger",
      store: [
              {
                reviews: [
                  {
                    name: "Lars Nilsen",
                    pictures: ["Media/Cities/Stavanger/Bakeri/Kundebilder/Kundebilde12.jpg"],
                    score: 5,
                    reviewText: "Kaffen var så god at jeg glemte å sjekke mobilen. Det skjer aldri.",
                    date: "2026-03-12",
                    likes: 19,
                    allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                  },
                  {
                    name: "Emma Berg",
                    pictures: [""],
                    score: 2,
                    reviewText: "Bestilte latte, fikk noe som smakte som mandag morgen.",
                    date: "2026-03-10",
                    likes: 7,
                    allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                  },
                ],
                info: {
                  city: "Stavanger",
                  storeName: "Kaffekroken",
                  type: "cafe",
                  pictures: ["Media/Cities/Stavanger/Bakeri/Bakeri21.jpg"],
                  address: "Øvre Holmegate 10",
                  phone: 51881212,
                  email: "hei@kaffekroken.no",
                  averageScore: 3.9,
                  reviewAmount: 132,
                  link: "https://kaffekroken.no",
                },
              },

              {
                reviews: [
                  {
                    name: "Mia Hansen",
                    pictures: [""],
                    score: 5,
                    reviewText: "Baksten er så god!",
                    date: "2026-03-11",
                    likes: 25,
                    allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                  },
                  {
                    name: "Per Johansen",
                    pictures: [""],
                    score: 3,
                    reviewText: "God smak, men jeg spiste for mye og skylder på dem.",
                    date: "2026-03-09",
                    likes: 10,
                    allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                  },
                ],
                info: {
                  city: "Stavanger",
                  storeName: "Bolle & Bønner",
                  type: "bakery",
                  pictures: ["Media/Cities/Stavanger/Bakeri/Bakeri10.jpg"],
                  address: "Breigata 14",
                  phone: 51887755,
                  email: "post@bollebonner.no",
                  averageScore: 4.4,
                  reviewAmount: 210,
                  link: "https://bollebonner.no",
                },
              },

              {
                reviews: [],
                info: {
                  city: "Stavanger",
                  storeName: "HavSmak Restaurant",
                  type: "restaurant",
                  pictures: ["Media/Cities/Stavanger/Resturant/Resturant10.jpg"],
                  address: "Skagenkaien 6",
                  phone: 51990022,
                  email: "kontakt@havsmak.no",
                  averageScore: 4.1,
                  reviewAmount: 45,
                  link: "https://havsmak.no",
                },
              },

              {
                reviews: [
                  {
                    name: "Karen Lie",
                    pictures: [""],
                    score: 1,
                    reviewText: "Maten kom sent.",
                    date: "2026-03-07",
                    likes: 1,
                    allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                  },
                  {
                    name: "Ole Strand",
                    pictures: ["Media/Cities/Bergen/Resturant/Kundebilder/Kundebilde11.jpg"],
                    score: 4,
                    reviewText: "God burger, men litt mye saus.",
                    date: "2026-03-06",
                    likes: 8,
                    allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                  },
                  {
                    name: "Nora Aas",
                    pictures: [""],
                    score: 5,
                    reviewText: "Elsker dette stedet! Kom sulten, trillet ut.",
                    date: "2026-03-05",
                    likes: 12,
                    allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                  },
                ],
                info: {
                  city: "Stavanger",
                  storeName: "BurgerBrygga",
                  type: "restaurant",
                  pictures: ["Media/Cities/Stavanger/Resturant/Resturant12.jpg"],
                  address: "Verksgata 9",
                  phone: 51776677,
                  email: "hei@burgerbrygga.no",
                  averageScore: 3.8,
                  reviewAmount: 167,
                  link: "https://burgerbrygga.no",
                },
              },

              {
                reviews: [
                  {
                    name: "Sofie Berg",
                    pictures: [""],
                    score: 4,
                    reviewText: "God pizza, men jeg brente tunga. Igjen.",
                    date: "2026-03-11",
                    likes: 6,
                    allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                  },
                  {
                    name: "Lars Hansen",
                    pictures: ["Media/Cities/Alta/Resturant/Kundebilder/Kundebilde1.jpg"],
                    score: 5,
                    reviewText: "Perfekt bunn og masse smak!",
                    date: "2026-03-09",
                    likes: 9,
                    allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                  },
                  {
                    name: "Jon Eriksen",
                    pictures: [""],
                    score: 3,
                    reviewText: "Helt greit, men ikke revolusjonerende.",
                    date: "2026-03-08",
                    likes: 3,
                    allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                  },
                ],
                info: {
                  city: "Stavanger",
                  storeName: "Steinovn Pizza",
                  type: "restaurant",
                  pictures: ["Media/Cities/Stavanger/Resturant/Resturant11.jpg"],
                  address: "Kirkegata 3",
                  phone: 51994411,
                  email: "hei@steinovnpizza.no",
                  averageScore: 4.0,
                  reviewAmount: 156,
                  link: "https://steinovnpizza.no",
                },
              },

              {
                reviews: [],
                info: {
                  city: "Stavanger",
                  storeName: "Søt Fristelse Stavanger",
                  type: "bakery",
                  pictures: ["Media/Cities/Stavanger/Bakeri/Bakeri11.jpg"],
                  address: "Pedersgata 20",
                  phone: 51885522,
                  email: "kontakt@sotfristelse.no",
                  averageScore: 4.5,
                  reviewAmount: 98,
                  link: "https://sotfristelse.no",
                },
              },

              {
                reviews: [
                  {
                    name: "Henrik Moe",
                    pictures: [""],
                    score: 1,
                    reviewText: "Pastaen var overkokt. Den hadde gitt opp før jeg gjorde det.",
                    date: "2026-03-08",
                    likes: 12,
                    allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                  },
                  {
                    name: "Kari Nilsen",
                    pictures: ["Media/Cities/Trondheim/Resturant/Kundebilder/Kundebilde6.jpg"],
                    score: 5,
                    reviewText: "Fantastisk pasta! Kommer tilbake.",
                    date: "2026-03-06",
                    likes: 9,
                    allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                  },
                ],
                info: {
                  city: "Stavanger",
                  storeName: "Pastahuset",
                  type: "restaurant",
                  pictures: ["Media/Cities/Stavanger/Resturant/Resturant13.jpg"],
                  address: "Kongsgata 18",
                  phone: 51775500,
                  email: "kontakt@pastahuset.no",
                  averageScore: 3.7,
                  reviewAmount: 109,
                  link: "https://pastahuset.no",
                },
              },
            ],
      }, 
      { name: "Alta",
      store: [
              {
                reviews: [
                  {
                    name: "Ole Hansen",
                    pictures: ["Media/Cities/Trondheim/Bakeri/Kundebilder/Kundebilde20.jpg"],
                    score: 5,
                    reviewText: "Kaffen var så sterk at jeg fortsatt er våken siden tirsdag, gudd stuff!.",
                    date: "2026-03-12",
                    likes: 16,
                    allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                  },
                  {
                    name: "Mia Berg",
                    pictures: [""],
                    score: 3,
                    reviewText: "Koselig sted, men jeg frøs litt… eller det er kanskje bare Alta.",
                    date: "2026-03-10",
                    likes: 8,
                    allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                  },
                ],
                info: {
                  city: "Alta",
                  storeName: "Nordlys Kaffehus",
                  type: "cafe",
                  pictures: ["Media/Cities/Alta/Bakeri/Bakeri20.jpg"],
                  address: "Markedsgata 12",
                  phone: 78451234,
                  email: "hei@nordlyskaffe.no",
                  averageScore: 4.1,
                  reviewAmount: 87,
                  link: "https://nordlyskaffe.no",
                },
              },

              {
                reviews: [
                  {
                    name: "Per Johansen",
                    pictures: [""],
                    score: 1,
                    reviewText: "Pizzaen var kald. Jeg ble kald. Alt var kaldt.",
                    date: "2026-03-11",
                    likes: 12,
                    allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                  },
                  {
                    name: "Anna Nilsen",
                    pictures: ["Media/Cities/Bergen/Resturant/Kundebilder/Kundebilde9.jpg"],
                    score: 4,
                    reviewText: "God smak, bare litt treg servering.",
                    date: "2026-03-09",
                    likes: 5,
                    allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                  },
                  {
                    name: "Jonas Vik",
                    pictures: [""],
                    score: 5,
                    reviewText: "Elsker dette stedet! Kommer tilbake (med jakke).",
                    date: "2026-03-08",
                    likes: 9,
                    allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                  },
                ],
                info: {
                  city: "Alta",
                  storeName: "Arktisk Pizza",
                  type: "restaurant",
                  pictures: ["Media/Cities/Tromsø/Resturant/Resturant15.jpg"],
                  address: "Altaveien 5",
                  phone: 78459876,
                  email: "post@arktiskpizza.no",
                  averageScore: 3.6,
                  reviewAmount: 143,
                  link: "https://arktiskpizza.no",
                },
              },

              {
                reviews: [],
                info: {
                  city: "Alta",
                  storeName: "Bakst & Kulde",
                  type: "bakery",
                  pictures: ["Media/Cities/Alta/Bakeri/Bakeri13.jpg"],
                  address: "Løkkeveien 3",
                  phone: 78457788,
                  email: "kontakt@bakstkulde.no",
                  averageScore: 4.4,
                  reviewAmount: 52,
                  link: "https://bakstkulde.no",
                },
              },

              {
                reviews: [
                  {
                    name: "Kari Lie",
                    pictures: [""],
                    score: 5,
                    reviewText: "Burgeren var så stor at jeg måtte ta pause halvveis.",
                    date: "2026-03-12",
                    likes: 14,
                    allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                  },
                  {
                    name: "Lars Strand",
                    pictures: ["Media/Cities/Alta/Resturant/Kundebilder/Kundebilde3.jpg"],
                    score: 2,
                    reviewText: "God burger, max saus!!",
                    date: "2026-03-10",
                    likes: 7,
                    allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                  },
                  {
                    name: "Nora Moe",
                    pictures: [""],
                    score: 4,
                    reviewText: "Veldig bra, men litt rotete bord.",
                    date: "2026-03-09",
                    likes: 3,
                    allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                  },
                ],
                info: {
                  city: "Alta",
                  storeName: "BurgerBasen",
                  type: "restaurant",
                  pictures: ["Media/Cities/Alta/Resturant/Resturant4.jpg"],
                  address: "Sentrumsgata 8",
                  phone: 78456677,
                  email: "hei@burgerbasen.no",
                  averageScore: 3.9,
                  reviewAmount: 119,
                  link: "https://burgerbasen.no",
                },
              },

              {
                reviews: [
                  {
                    name: "Emma Hansen",
                    pictures: [""],
                    score: 5,
                    reviewText: "Kakene var så gode at jeg glemte nyttårsforsettet mitt.",
                    date: "2026-03-11",
                    likes: 18,
                    allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                  },
                  {
                    name: "Henrik Berg",
                    pictures: ["Media/Cities/Alta/Bakeri/Kundebilder/Kundebilde10.jpg"],
                    score: 3,
                    reviewText: "Bra smak, men litt små porsjoner.",
                    date: "2026-03-09",
                    likes: 4,
                    allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                  },
                ],
                info: {
                  city: "Alta",
                  storeName: "Søt Nord",
                  type: "bakery",
                  pictures: ["Media/Cities/Alta/Bakeri/Bakeri9.jpg"],
                  address: "Parkveien 2",
                  phone: 78459911,
                  email: "post@sotnord.no",
                  averageScore: 4.2,
                  reviewAmount: 76,
                  link: "https://sotnord.no",
                },
              },

              {
                reviews: [],
                info: {
                  city: "Alta",
                  storeName: "FjordSmak",
                  type: "restaurant",
                  pictures: ["Media/Cities/Alta/Resturant/Resturant8.jpg"],
                  address: "Havneveien 6",
                  phone: 78452233,
                  email: "kontakt@fjordsmak.no",
                  averageScore: 4.0,
                  reviewAmount: 33,
                  link: "https://fjordsmak.no",
                },
              },

              {
                reviews: [
                  {
                    name: "Sofie Vik",
                    pictures: [""],
                    score: 4,
                    reviewText: "God kaffe, god bakst, men litt trangt lokale.",
                    date: "2026-03-10",
                    likes: 5,
                    allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                  },
                  {
                    name: "Daniel Aas",
                    pictures: [""],
                    score: 1,
                    reviewText: "Bestilte te, fekk no som smakte som varmt katta pess.",
                    date: "2026-03-08",
                    likes: 11,
                    allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                  },
                  {
                    name: "Mats Nilsen",
                    pictures: [""],
                    score: 5,
                    reviewText: "Perfekt sted å varme seg etter kulda!",
                    date: "2026-03-07",
                    likes: 9,
                    allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                  },
                ],
                info: {
                  city: "Alta",
                  storeName: "Varm Kopp",
                  type: "cafe",
                  pictures: ["Media/Cities/Alta/Bakeri/Bakeri19.png"],
                  address: "Torget 1",
                  phone: 78458899,
                  email: "hei@varmkopp.no",
                  averageScore: 3.8,
                  reviewAmount: 98,
                  link: "https://varmkopp.no",
                },
              },

              {
                reviews: [],
                info: {
                  city: "Alta",
                  storeName: "Vaffelhjørnet Alta",
                  type: "cafe",
                  pictures: ["Media/Cities/Alta/Bakeri/Bakeri17.jpg"],
                  address: "Elvebakken 4",
                  phone: 78453322,
                  email: "hei@vaffelalta.no",
                  averageScore: 4.3,
                  reviewAmount: 65,
                  link: "https://vaffelalta.no",
                },
              },

              {
                reviews: [
                  {
                    name: "Per Vik",
                    pictures: ["Media/Cities/Alta/Resturant/Kundebilder/Kundebilde14.jpg"],
                    score: 4,
                    reviewText: "God smak, men litt dyrt.",
                    date: "2026-03-07",
                    likes: 4,
                    allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                  },
                  {
                    name: "Emma Lie",
                    pictures: [""],
                    score: 5,
                    reviewText: "Fantastisk middag! Kommer igjen.",
                    date: "2026-03-06",
                    likes: 7,
                    allergyList: {
                        vegan: false,
                        milk: false,
                        nuts: false,
                        wheat: false,
                               },
                  },
                ],
                info: {
                  city: "Alta",
                  storeName: "Pastahuset Nord",
                  type: "restaurant",
                  pictures: ["Media/Cities/Alta/Resturant/Resturant9.jpg"],
                  address: "Sentrum 15",
                  phone: 78456611,
                  email: "kontakt@pastahusetnord.no",
                  averageScore: 3.8,
                  reviewAmount: 124,
                  link: "https://pastahusetnord.no",
                },
              },
            ],
      }, 
    ],
  },
};





